### ISSUE TITLE
Backend - Upgrade to Spring 5 & Spring Boot 2

### ISSUE THREAD

**Issue by yodamad** [suricate-io/suricate#203]
### Subject of the issue
Describe your issue here.

#### Issue type
[] Bug
[X] Improvment
[] Documentation
[] Feature

**NB**: Specify labels in right panel also

### Expected behaviour
Migration to newer version of Spring framework components

**Comment by yodamad** [comment]
@Juyoo Here is the stack :

`javax.persistence.EntityNotFoundException: Unable to find io.suricate.monitoring.model.entity.Configuration with id WIDGET_CONFIG_GITLAB_TOKEN
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:159)
	at org.hibernate.proxy.AbstractLazyInitializer.checkTargetState(AbstractLazyInitializer.java:244)
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:166)
	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:268)
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:73)
	at io.suricate.monitoring.model.entity.Configuration_$$_jvst7cc_6.getValue(Configuration_$$_jvst7cc_6.java)
	at io.suricate.monitoring.service.api.ConfigurationService.addOrUpdateConfiguration(ConfigurationService.java:159)
	at io.suricate.monitoring.service.api.ConfigurationService.lambda$addOrUpdateConfigurations$0(ConfigurationService.java:174)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.suricate.monitoring.service.api.ConfigurationService.addOrUpdateConfigurations(ConfigurationService.java:174)
	at io.suricate.monitoring.service.api.ConfigurationService$$FastClassBySpringCGLIB$$fed9c014.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at io.suricate.monitoring.service.api.ConfigurationService$$EnhancerBySpringCGLIB$$99938ad8.addOrUpdateConfigurations(<generated>)
	at io.suricate.monitoring.service.api.CategoryService.addOrUpdateCategory(CategoryService.java:138)
	at io.suricate.monitoring.service.api.CategoryService$$FastClassBySpringCGLIB$$2e0c0382.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at io.suricate.monitoring.service.api.CategoryService$$EnhancerBySpringCGLIB$$6829768a.addOrUpdateCategory(<generated>)
	at io.suricate.monitoring.service.api.WidgetService.updateWidgetInDatabase(WidgetService.java:212)
	at io.suricate.monitoring.service.api.WidgetService$$FastClassBySpringCGLIB$$b987fa3c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at io.suricate.monitoring.service.api.WidgetService$$EnhancerBySpringCGLIB$$339fd250.updateWidgetInDatabase(<generated>)
	at io.suricate.monitoring.service.GitService.updateWidgetFromGit(GitService.java:187)`

**Comment by yodamad** [comment]
@Juyoo : Fix it, regression due to migration (Don't use `getOne` to replace `findOne` !!! but use `findById`
